# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69ab9ad3790c3e05255e5d4a879cf34900a490ca5c79ac79757dd5894f1f69b47998b22dee701df2161678948c07cd82f409720935d725bd1842fe517f9f923d

test:
  secret_key_base: 04b8a648d71c72b86d2d85a69d7d44f94a7e1598228644333f86471c1f0bf5713fa7aba62fd9bd7abba0f9379e0238a94e569e2af347482d35b9d3390bb0e5bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
